### ISSUE TITLE
Automatically create Windows Builds

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/mqtt-dmx-controller#1]
Does anyone want this? :)

**Comment by johnroper100** [comment]
Yes please.

**Comment by hobbyquaker** [comment]
I created a Windows build, you can find a setup .exe under https://github.com/hobbyquaker/mqtt-dmx-controller/releases/latest
I didn't test it until now, have to setup a Windows VM first.

**Comment by johnroper100** [comment]
I just ran with npm start on Windows and it works fine
