### ISSUE TITLE
How to use the MQTT interface

### ISSUE THREAD

**Issue by johnroper100** [hobbyquaker/mqtt-dmx-controller#3]
I am guessing that the MQTT interface is a web/mobile interface? How can I use it?

**Comment by hobbyquaker** [comment]
MQTT is a Messaging Protocol, it's kind of _the_ standard protocol for "Internet of Things" communications. You can find further Info and a lot of links to MQTT related software in this list: https://github.com/hobbyquaker/awesome-mqtt
